name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build all utilities
      run: make clean && make

    - name: Run smoke tests
      run: bash tests/run_smoke.sh

    - name: Run extended tests
      run: |
        chmod +x scripts/extended_tests.sh
        bash scripts/extended_tests.sh

    - name: Check compilation warnings
      run: |
        make clean
        make 2>&1 | grep -i warning && exit 1 || true
